// Usage: npm run build
// Copies data/*.json into data/season-data.js so index.html works from a folder (browsers block fetch on file://).
const fs = require('node:fs');
const path = require('node:path');

const dir = path.join(__dirname, '..', 'data');
const read = (file) => JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));
const out = `// Generated by scripts/build-data.js from games.json and schedule.json. Do not edit.\nwindow.BaflData = ${JSON.stringify({ games: read('games.json'), schedule: read('schedule.json') })};\n`;
fs.writeFileSync(path.join(dir, 'season-data.js'), out);
console.log('Wrote data/season-data.js');
